name: Rust

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]
        profile: [release, debug]
    steps:
    - uses: actions/checkout@v3
    - uses: paulloz/godot-action@v1.2
      name: Install Godot 4
      with:
        version: 4.0.1
    - name: Build
      run: cargo build --verbose --target ${{matrix.target}} --${{ matrix.profile }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: |
          target/*/*/*.so
          target/*/*/*.dll
          target/*/*/*.dylib
  build-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
        profile: [release, debug]
    steps:
    - uses: actions/checkout@v3
    - uses: paulloz/godot-action@v1.2
      name: Install Godot 4
      with:
        version: 4.0.1
    - name: Build
      run: cargo build --verbose --target ${{matrix.target}} --${{ matrix.profile }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: |
          target/*/*/*.so
          target/*/*/*.dll
          target/*/*/*.dylib
  release:
    runs-on: ubuntu-latest
    name: Upload to Github
    needs: [build, build-mac]
    steps:
    - uses: actions/download-artifact@v2.0.8
      with:
        name: target
        path: target
    - name: Copy artifacts into place
      runs: |
        mkdir -p gamesheet_libs/{debug,release}
        cp $(find target/*/debug -name '*.so' -or -name '*.dll' -or -name '*.dylib' -and -name '*gd*') gamesheet_libs/debug
        cp $(find target/*/release -name '*.so' -or -name '*.dll' -or -name '*.dylib' -and -name '*gd*') gamesheet_libs/release
    - name: Zip artifacts
      runs: |
        zip -r gamesheet_libs gamesheet_libs
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "gamesheet_libs.zip"
